# Generated by Django 5.0.3 on 2025-11-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
