# Generated by Django 5.0.3 on 2025-11-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_user_university_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
